version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          # The Amazon ECR account URL that maps to an AWS account, e.g. {awsAccountNum}.dkr.ecr.us-west-2.amazonaws.com
          account-url: AWS_ECR_ACCOUNT_URL
          # AWS access key id for IAM role. Set this to the name of the environment variable you will set to hold this value, i.e. AWS_ACCESS_KEY.
          aws-access-key-id: AWS_ACCESS_KEY
          # AWS secret key for IAM role. Set this to the name of the environment variable you will set to hold this value, i.e. AWS_SECRET_ACCESS_KEY.
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          # Should the repo be created if it does not exist?
          create-repo: true
          # Name of dockerfile to use. Defaults to Dockerfile.
          dockerfile: Dockerfile
          # Path to the directory containing your Dockerfile and build context. Defaults to . (working directory).
          path: .
          # Name of env var storing your AWS region information, defaults to AWS_REGION
          region: AWS_REGION
          # Name of an Amazon ECR repository
          repo: circleci-ecr-orb-demo
          # A comma-separated string containing docker image tags to build and push (default = latest)
          # Consider using $CIRCLE_BUILD_NUM
          tag: "$CIRCLE_BUILD_NUM"
